# Generated by Django 5.2.3 on 2025-06-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.CharField(choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag')], default='Mo', max_length=10, verbose_name='Wochentag')),
                ('startzeit', models.TimeField(verbose_name='Startzeit')),
                ('endzeit', models.TimeField(verbose_name='Endzeit')),
                ('nach_vereinbarung', models.BooleanField(default=False, verbose_name='Nach Vereinbarung')),
            ],
            options={
                'verbose_name': 'Sprechzeit',
                'verbose_name_plural': 'Sprechzeiten',
            },
        ),
        migrations.CreateModel(
            name='FreeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.CharField(choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag')], default='Mo', max_length=10, verbose_name='Wochentag')),
                ('startzeit', models.TimeField(verbose_name='Startzeit')),
                ('endzeit', models.TimeField(verbose_name='Endzeit')),
            ],
            options={
                'verbose_name': 'Freie Annahme',
                'verbose_name_plural': 'Freie Annahmen',
            },
        ),
        migrations.CreateModel(
            name='PracticeClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datum', models.DateField(verbose_name='Startdatum')),
                ('end_datum', models.DateField(verbose_name='Enddatum')),
            ],
            options={
                'verbose_name': 'Praxisschließzeit',
                'verbose_name_plural': 'Praxisschließzeiten',
            },
        ),
    ]
