# Generated by Django 5.2.3 on 2025-06-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('betreff', models.CharField(max_length=200, verbose_name='Betreff')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingereicht am')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
            },
        ),
    ]
